### PR TITLE
feat: added `AsyncResource` factory function option

### PR DESCRIPTION
**Pull request by imjuni**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Eomm** [comment]
Could you update the PR?
The CI should be green now

**Comment by imjuni** [comment]
Updated

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by imjuni** [comment]
Is there anything else I should do?

**Comment by mcollina** [comment]
Nope, it's in our queue for shipping a releass

**Pull request merged**
