### PR TITLE
fix linting

### PR DESCRIPTION
**Pull request by Uzlopak**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by gurgunday — COMMENTED** [review]
Looks good but index.js is also in the prettier script, is that intentional?

**Review by Eomm — APPROVED** [review]
I will die without seeing prettier and eslint working fine together on the first try.

**Comment by Uzlopak** [comment]
If it would me, I would just rip out prettier and eslint and just use standard. but then people would complain that typescript files are not linted. So I just do this minimal patch, to get the CI green.

@gurgunday 
index.js contains code. Is it wrong?

**Comment by gurgunday** [comment]
Yeah but I thought eslint was using standard for .js files

**Review by gurgunday — APPROVED** [review]

**Comment by gurgunday** [comment]
@Eomm I'm really proud of this config that uses standard for everything except formatting 😁

```json
{
  "root": true,
  "extends": ["standard", "prettier"],
  "plugins": ["github", "prettier"],
  "rules": {
    "no-restricted-syntax": [
      "error",
      "MethodDefinition[kind='get']",
      "MethodDefinition[kind='set']",
      "VariableDeclaration[kind='var']",
      "WithStatement"
    ],
    "github/array-foreach": "error",
    "class-methods-use-this": "error",
    "prefer-const": "error",
    "prefer-destructuring": "error",
    "prefer-exponentiation-operator": "error",
    "prefer-named-capture-group": "error",
    "prefer-numeric-literals": "error",
    "prefer-object-has-own": "error",
    "prefer-object-spread": "error",
    "prefer-promise-reject-errors": "error",
    "prefer-regex-literals": "error",
    "prefer-rest-params": "error",
    "prefer-spread": "error",
    "prefer-template": "error",
    "prettier/prettier": "error",
    "arrow-body-style": "error",
    "curly": ["error", "all"],
    "quotes": ["error", "double", { "avoidEscape": true }]
  }
}
```

**Comment by Fdawgs** [comment]
> I'm really proud of this config that uses standard for everything except formatting, which prettier takes care of 😁

https://github.com/prettier/eslint-config-prettier ?

**Comment by Eomm** [comment]
Here is my setup standard + typescript:

```
"lint:typescript": "standard --parser @typescript-eslint/parser --plugin @typescript-eslint/eslint-plugin *.ts test/**/*.ts",
```

**Pull request merged**
