### PR TITLE
migrate to github actions

### PR DESCRIPTION
**Pull request by Eomm**
As titled

### CODE REVIEW

**Comment by kibertoad** [comment]
Thanks! Do I need to enable it somewhere?

**Comment by kibertoad** [comment]
@Eomm Could you stop building CircleCI project? It is failing now due to the lack of configuration, and apparently admin permissions for `fastify` are needed for that, which I do not have.

**Comment by Eomm** [comment]
> Could you stop building CircleCI project?

I don't have right for that, @mcollina should have it.

> Thanks! Do I need to enable it somewhere?

No, the action started after the merge: https://github.com/fastify/fastify-request-context/actions

**Comment by mcollina** [comment]
done!

**Pull request merged**
